### ISSUE TITLE
Compiled, built and installed, but how to use?

### ISSUE THREAD

**Issue by zenny** [norihiro/obs-audio-pan-filter#1]
Hi @norihiro ,

Thanks for this useful plugin. I compiled, built and installed the plugin, and loaded a stereo audio with two channels as a source to a scene, but a window like https://obsproject.com/forum/attachments/stereo-pan-filter-config-png.59155/ didn't pop up. Did I miss something?

Cheers, and stay safe,
/z

**Comment by norihiro** [comment]
This is a plugin as a filter. You need to add the stereo-pan effect to a filter chain for the source. The steps would be
1. Right click the source (or click gear icon in Audio Mixer) and click `Filters`.
2. Click `+` icon and add `Stereo Pan`.
3. Adjust your volume and pan for each channel.

I will find a suitable place to put the instruction.

**Comment by norihiro** [comment]
The same instruction is added to the forum page.

https://obsproject.com/forum/resources/audio-pan-filter.1042/
